### ISSUE TITLE
I'd like if you make it Apache License 2.0 because of it is simple

### ISSUE THREAD

**Issue by zubairmahdihatef** [mmustafasesudia/WhatsApp-Status-Saver#3]
I think Apache License 2.0 is simple to integrate

So, please mark it as the license of the project

thank you

**Comment by mmustafasesudia** [comment]
> I think Apache License 2.0 is simple to integrate
> 
> So, please mark it as the license of the project
> 
> thank you

Done.

**Comment by mmustafasesudia** [comment]
> I think Apache License 2.0 is simple to integrate
> 
> So, please mark it as the license of the project
> 
> thank you

Done
